package codebase22;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class AsgUtils {

	/**
	 * This is a salt generated by generating a UUID once and it was then stored
	 * here manually.
	 */
	

	/**
	 * Hashes a password and a salt using md5, fast and effective
	 * 
	 * @param passwordToHash
	 *            Plaintext password.
	 * @param salt
	 *            Salt to add to the password
	 * 
	 * @return The hash of the salt and the password.
	 */
	public static String simpleHash(String passwordToHash, String salt) {
		String comboPass = salt + passwordToHash;
		String generatedPassword = null;

		try {
			MessageDigest md = MessageDigest.getInstance("MD5");
			md.update(comboPass.getBytes());
			byte[] bytes = md.digest();
			StringBuilder sb = new StringBuilder();

			// hex hash
			for (int i = 0; i < bytes.length; i++) {
				sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
			}
			generatedPassword = sb.toString();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}

		return generatedPassword;
	}

}
